<a href="https://colab.research.google.com/github/SiddhantUke/PYTHON_REVISE/blob/main/Sect_13_(54_Numpy_in_Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
 ## For installation of numpy


In [2]:
!pip install numpy



In [3]:
## Provide  support for arrays and matrices !

# for import

import numpy as np



In [4]:
## Create array using Numpy
## Create 1D array


arr1 = np.array([1,2,3,4,5]) ## This actually help to create an array ie np.array() ie called functn !


## Inside this i can create list and tuples !

print(arr1)

print(type(arr1))  ## Basically n dimension array !

print(arr1.shape)  ##  If we want to see the shape of an  array !

## When we get a single dimension we can say that no specific column or rows are there  !



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
## How it becomes the 2D array !


arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)


## How if we want to reshape it 5 element that is in 1,5

# 1 row and 5 column


array([[1, 2, 3, 4, 5]])

In [6]:
## what if we want to do it directly !

arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## what if add more list in this !

arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)
print(arr2.shape)

# 2 rows and 5 column !

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [8]:
## Create an Array with an Inbuilt Function !

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
## inbuilt fucntn  Present In NUMPY ARRAY that !

np.ones((3,4))

## create 2D array with 3 rows and 4 column !

##

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## Identity Matrix and array to create !

np.eye(3)

## All Diagonal element is 1 and other is zero !



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)

print("Shape:", arr.shape)  # Output: (2, 3)

print("Number of dimensions:", arr.ndim)  # Output: 2

print("Size (number of elements):", arr.size)  # Output: 6

print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)

print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
## Numpy Vectorized Operation !

arr1 = np.array([1,2,3,4,5])

arr2 = np.array([10,20,30,40,50])


## ElementWise Addition !

print("Addition:", arr1+arr2)

## Element Wise Substraction !

print("Multiplication:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Multiplication: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Functn
arr = np.array([2,3,4,5,6])

## Square Root
print(np.sqrt(arr))


## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
## Array Slicing andIndexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
## How do we access and pick up the single element from the array !

arr[0:1]

arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [16]:
## How do we pickup the element like 7 8 11 12 ?

arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [17]:
## Modufy the array element !

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:]=10
print(arr)

[[100   2   3   4]
 [ 10  10  10  10]
 [ 10  10  10  10]]


In [22]:
## Practical Operation - Normalization

# Chnage  to have a mean of 0 and standard deviation of 1


# Calculate the mean and standard deviation

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [26]:
## Logical Operation !

## Logical operation

data=np.array([1,2,3,4,5,6,7,8,9,10])

## Applying  the logical operation !

data>5 ## Boolean vlaue !

data[(data>5) & (data<8)] ## from this data which is greater than 5 !



array([6, 7])

NEXT IS PANDAS IN PYTHON !